version: '3.7'

services:
  app:
    build:
      context: ./backend
    container_name: laravel-app
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chat_app
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
